# Generated by Django 4.2.7 on 2025-04-08 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payments_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счёт')], max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
