# Generated by Django 4.2.7 on 2025-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
