# Generated by Django 4.2.7 on 2025-03-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_drf', '0002_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
